[package]
name = "titan-text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.83"
fontdb = "0.17.0"
lazy_static = "1.4.0"
swash = "0.1.15"
thiserror = "1.0.60"
wgpu = "0.20.0"
